version: 2
updates:
  # pnpm パッケージの更新設定
  # pnpmでもpackage-ecosystemは"npm"を使用
  - package-ecosystem: "npm"
    directory: "/"
    # 更新のスケジュール設定
    schedule:
      interval: "monthly" #毎月更新
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "automated"
      - "pnpm"
    # バージョン戦略の設定
    versioning-strategy: "increase"
    # 依存関係をグループ化して1つのPRにまとめる
    groups:
      #　すべてを1つのPRにまとめる
      all-updates:
        patterns:
          - "*"
