# Dependabot設定ファイル
# 依存関係の自動更新を管理するGitHubの機能
version: 2
updates:
  # パッケージの更新設定(pnpmでもnpmを使用する)
  - package-ecosystem: "npm"
    # 監視対象のディレクトリ（プロジェクトルート）
    directory: "/"
    schedule:
      interval: "monthly"

    # 同時に開けるプルリクエストの最大数を制限
    open-pull-requests-limit: 5

    # 特定の更新タイプを無視する設定
    # メジャーアップデートを無効化（破壊的変更の可能性があるため）
    ignore:
      # 全ての依存関係に対して
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

    # 複数の更新を1つのプルリクエストにまとめる設定
    groups:
      # マイナーアップデートとパッチアップデートのグループ
      minor-and-patch-updates:
        # 対象となるパッケージのパターン
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
